spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:

    defer-datasource-initialization: true
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true